version: '1'

services:
  frontend:
    build:
      context: ./sys-stats
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
